language: node_js
node_js:
  - '13'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./cc-test-reporter format-coverage -t lcov coverage/lcov.info -o coverage/codeclimate.json; fi'
  - yarn build:rollup
  - yarn build:storybook

after_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./cc-test-reporter upload-coverage; fi'

before_deploy:
  - 'cp -R ./docs ./storybook-static'

deploy:
  - provider: pages
    local_dir: storybook-static
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true