name: Publish packages

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  publish-packages:
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/master'
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        uses: changesets/action@v1
        id: changesets
        with:
          version: pnpm version
          publish: pnpm tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    outputs:
      ref: ${{ github.ref }}
      published: ${{ steps.changesets.outputs.published }}

  deliver-packages:
    name: Deliver packages
    uses: ./.github/workflows/cd-registries.yaml
    needs: publish-packages
    with:
      ref: ${{ needs.publish-packages.outputs.ref }}
    secrets: inherit
    if: ${{ needs.publish-packages.outputs.published }}

  deploy-to-static-file-host:
    name: Deploy to Static File Host
    uses: ./.github/workflows/cd-deploy.yaml
    needs: publish-packages
    with:
      ref: ${{ needs.publish-packages.outputs.ref }}
    if: ${{ needs.publish-packages.outputs.published }}
