name: Check size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    name: Check sizes
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
